### ISSUE TITLE
[Bug] Conflict caused by FALSE, TRUE macros and bool_tag enum using same name

### ISSUE THREAD

**Issue by XSven** [arithy/packcc#37] opened 2021-06-01 11:13 UTC
I am unabled to build packcc on AIX 7.2 using gcc version 8.3.0. The details are described here

[3044](https://github.com/universal-ctags/ctags/issues/3044)

This issue was closed/rejected because I thought this is a bug in universal-ctags, which is not the case. This is the complete output of the **make** run

```
mkdir -p debug/bin/ && gcc -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wno-overlength-strings -pedantic -O0 -g2 -o debug/bin/packcc ../../src/packcc.c
In file included from /opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8.3.0/include-fixed/stdio.h:503,
                 from ../../src/packcc.c:40:
../../src/packcc.c:94:5: error: expected identifier before numeric constant
     FALSE = 0,
     ^~~~~
../../src/packcc.c: In function 'unescape_string':
../../src/packcc.c:621:31: warning: comparison is always false due to limited range of data type [-Wtype-limits]
                         if (d < 0) break;
                               ^
../../src/packcc.c:647:31: warning: comparison is always false due to limited range of data type [-Wtype-limits]
                         if (d < 0) break;
                               ^
../../src/packcc.c:672:39: warning: comparison is always false due to limited range of data type [-Wtype-limits]
                                 if (d < 0) break;
                                       ^
../../src/packcc.c: In function 'populate_bits':
../../src/packcc.c:914:12: warning: right shift count >= width of type [-Wshift-count-overflow]
     x |= x >> 32;
            ^~
make: *** [Makefile:34: debug/bin/packcc] Error 1

```

**Comment by XSven** [comment] 2021-06-02 05:59
Answer to (1)
The header file /opt/freeware/lib/gcc/powerpc-ibm-aix7.2.0.0/8.3.0/include-fixed/sys/types.h defines the FLASE and TRUE macros [types.h.txt](https://github.com/arithy/packcc/files/6582195/types.h.txt).

Answer to (2)
I have compiled
```
#include <stdio.h>
int main(void) {
        printf("%d\n", (char)-1 < 0);
        return 0;
}
```
with

`gcc -std=gnu89 -Wall -Wextra -Wno-unused-parameter -Wno-overlength-strings -pedantic -O0 -g2 main.c`

Executing a.out returns 0 (false). That means char type is not a signed integer type. Using the compiler option -fsigned-char the result is 1 (true).

Answer to (3)

```
echo | gcc -std=gnu89 -dM -E - | grep __SIZEOF_SIZE_T__
#define __SIZEOF_SIZE_T__ 4

```

**Comment by arithy** [comment] 2021-06-02 09:16
Thanks for the information.

--

__About (1):__

OK, AIX's `sys/types.h` header file defines the macros.
I think that it's none of AIX's business.
Anyway, they might exist due to historical reasons.

Can you insert `undef` lines in `packcc.c` as follows?

~~~~C
  #ifndef __attribute__
  #define __attribute__(x)
  #endif

+ #undef TRUE
+ #undef FALSE

  #define VERSION "1.5.0"
~~~~

__About (2):__

As you said, can you add `-fsigned-char` compiler option?
I didn't know that there are platforms where the default `char` type is unsigned even in C.

__About (3);__

Currently, I don't find the cause of the warning of `x |= x >> 32;`.
This line should be excluded by `#if` directive when `size_t` is a 4-byte data type.

~~~~C
#if (defined __SIZEOF_SIZE_T__ && __SIZEOF_SIZE_T__ == 8) /* gcc or clang */ || defined _WIN64 /* MSVC */
    x |= x >> 32;
#endif
~~~~

Can you investigate this unexpected behavior using gcc for AIX?

--

I'll commit the modifications, after you confirmed that compilation and execution are successfully done.

**Comment by arithy** [comment] 2021-06-02 10:37
__About (3):__

I forgot to push the commit 6035daabaccc85b74664b51c270c8aec6f22e56d.
`#if ... || !defined _M_IX86` --> `#if ... || defined _WIN64`
This should fix the problem regarding `x |= x >> 32;`.
Please confirm it.

**Comment by arithy** [comment] 2021-06-02 15:22
I pushed the commits that might fix this issue.
Can you confirm compilation and execution on your AIX environment?
~~~~
cd build/gcc
make
make check  # bats-core and uncrustify are required (see tests/README.md)
~~~~

**Comment by XSven** [comment] 2021-06-03 06:10
**make** runs without any issue. As you have already noticed I am not able to run **make check** due to the missing tools. If you don't mind (?!) I am skipping this because this drives me too far away from my original goal to compile universal-ctags that packcc was a part of.

I am considering this issue as solved. Thanks for your help.

**Comment by arithy** [comment] 2021-06-03 10:10
OK, I close this issue.

**Closed by arithy** 2021-06-03 10:10 UTC
